valor = input('Digite Algo: ')
print('É Alfanumérico: ', valor.isalnum())
print('É Alfabético: ', valor.isalpha())
print('É ASCII: ', valor.isascii())
print('É Decimal: ', valor.isdecimal())
print('É um Dígito: ', valor.isdigit())
print('É um Indentificador: ', valor.isidentifier())
print('Está em Minúsculas: ', valor.islower()),
print('É Numérico: ', valor.isnumeric())
print('É printable: ', valor.isprintable())
print('É capitalizada: ', valor.istitle())
print('Está em Maiúsculas: ', valor.isupper())